<a href="https://colab.research.google.com/github/pruthviraj3715/Artificial_Intelligence_Lab_SE_A_49/blob/master/EXPERIMENT_3_(matrices_%2C_determinant_and_inverse).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solution of a System of Linear Equations Using Matrix Inverse Method (Without NumPy)

Aim:
### To find the determinant, inverse of a 3×3 matrix, and to solve a system of three linear equations using pure Python without external libraries.

In [1]:
print("Given System of Linear Equations:")
print("1) 2x + y + 3z = 13")
print("2) x  + 2y + z = 9")
print("3) 3x + y + 2z = 13")

A = [
    [2, 1, 3],
    [1, 2, 1],
    [3, 1, 2]
]

B = [13, 9, 13]

def determinant(A):
    a,b,c = A[0]
    d,e,f = A[1]
    g,h,i = A[2]
    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

def inverse(A):
    a,b,c = A[0]
    d,e,f = A[1]
    g,h,i = A[2]
    det = determinant(A)

    return [
        [(e*i-f*h)/det, (c*h-b*i)/det, (b*f-c*e)/det],
        [(f*g-d*i)/det, (a*i-c*g)/det, (c*d-a*f)/det],
        [(d*h-e*g)/det, (b*g-a*h)/det, (a*e-b*d)/det]
    ]

def solve(invA, B):
    x = invA[0][0]*B[0] + invA[0][1]*B[1] + invA[0][2]*B[2]
    y = invA[1][0]*B[0] + invA[1][1]*B[1] + invA[1][2]*B[2]
    z = invA[2][0]*B[0] + invA[2][1]*B[1] + invA[2][2]*B[2]
    return x, y, z

print("\nCoefficient Matrix A:")
print(A[0])
print(A[1])
print(A[2])

detA = determinant(A)
print("\nDeterminant of Matrix A:", detA)

invA = inverse(A)
print("\nInverse of Matrix A:")
print(invA[0])
print(invA[1])
print(invA[2])

x, y, z = solve(invA, B)
print("\nSolution of the given equations:")
print("x =", round(x, 2))
print("y =", round(y, 2))
print("z =", round(z, 2))


Given System of Linear Equations:
1) 2x + y + 3z = 13
2) x  + 2y + z = 9
3) 3x + y + 2z = 13

Coefficient Matrix A:
[2, 1, 3]
[1, 2, 1]
[3, 1, 2]

Determinant of Matrix A: -8

Inverse of Matrix A:
[-0.375, -0.125, 0.625]
[-0.125, 0.625, -0.125]
[0.625, -0.125, -0.375]

Solution of the given equations:
x = 2.12
y = 2.38
z = 2.12


# Solution of a System of Linear Equations Using Matrix Inverse Method (Using NumPy)

Aim:
### To compute the determinant, inverse of a 3×3 matrix, and to solve a system of three linear equations using NumPy’s built-in linear algebra algorithms.

In [2]:
import numpy as np

print("Given System of Linear Equations:")
print("1) 2x + y + 3z = 13")
print("2) x  + 2y + z = 9")
print("3) 3x + y + 2z = 13")

A = np.array([
    [2, 1, 3],
    [1, 2, 1],
    [3, 1, 2]
])

B = np.array([13, 9, 13])

print("\nCoefficient Matrix A:")
print(A)

print("\nConstant Matrix B:")
print(B)

detA = np.linalg.det(A)
print("\nDeterminant of Matrix A:", round(detA, 2))

invA = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(np.round(invA, 2))

solution = np.linalg.solve(A, B)
print("\nSolution of the given equations:")
print("x =", round(solution[0], 2))
print("y =", round(solution[1], 2))
print("z =", round(solution[2], 2))


Given System of Linear Equations:
1) 2x + y + 3z = 13
2) x  + 2y + z = 9
3) 3x + y + 2z = 13

Coefficient Matrix A:
[[2 1 3]
 [1 2 1]
 [3 1 2]]

Constant Matrix B:
[13  9 13]

Determinant of Matrix A: -8.0

Inverse of Matrix A:
[[-0.38 -0.12  0.62]
 [-0.13  0.62 -0.12]
 [ 0.62 -0.12 -0.38]]

Solution of the given equations:
x = 2.12
y = 2.38
z = 2.12
